arrowParens: avoid
bracketSpacing: false
# endOfLine: lf
# htmlWhitespaceSensitivity: css
insertPragma: false
# parser: babel
printWidth: 120
proseWrap: never
quoteProps: as-needed
requirePragma: false
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: true
